name: IOOS
channels:
    - ioos
dependencies:
    - basemap
    - beautifulsoup4
    - cartopy
    - ctd
    - cython
    - descartes
    - fiona
    - folium
    - gdal
    - geojson
    - geojsonio
    - geopandas
    - gsw
    - iris
    - jupyter
    - matplotlib
    - mpld3
    - mplleaflet
    - numpy
    - oceans
    - oct2py
    - owslib
    - paegan
    - paegan-transport
    - pandas
    - pip
    - proj4
    - pyoos
    - pyproj
    - pysgrid
    - pyugrid
    - pywafo
    - qrcode
    - rasterio
    - rdflib
    - requests
    - rtree
    - scikit-learn
    - scipy
    - seaborn
    - shapely
    - statsmodels
    - sympy
    - utilities
    - xlrd
    - yaml
